//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace No1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=dene;dbq=C:\\USERS\\ALIKO\\ONEDRIVE\\MASAÜSTÜ\\Lesson\\c#\\c# çalışmalarım\\program t" +
            "aslak.xlsx;defaultdir=C:\\USERS\\ALIKO\\ONEDRIVE\\MASAÜSTÜ\\Lesson\\c#\\c# çalışmalarım" +
            ";driverid=1046;fil=excel 12.0;maxbuffersize=2048;pagetimeout=5")]
        public string exceldeneme {
            get {
                return ((string)(this["exceldeneme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-83AGMDV\\MSSQLSERVER61;Initial Catalog=cafedata;Integrated Sec" +
            "urity=True")]
        public string cafedataConnectionString {
            get {
                return ((string)(this["cafedataConnectionString"]));
            }
        }
    }
}
